name: travellingg_viajes
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.1.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_login: ^4.2.1
    flutter_zoom_drawer: ^3.1.1
    get: ^4.6.5
    intl: ^0.18.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    assets:
        - lib/assets/
        - lib/assets/countries/
