name: travellingg_viajes
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.1.0 <4.0.0"

dependencies:
    carousel_slider: ^4.2.1
    flutter:
        sdk: flutter
    flutter_credit_card: ^3.0.7
    flutter_form_builder: ^9.1.0
    flutter_launcher_icons: ^0.13.1
    flutter_localizations:
        sdk: flutter
    flutter_login: ^4.2.1

    flutter_zoom_drawer: ^3.1.1
    form_builder_validators: ^9.0.0
    get: ^4.6.5
    intl: ^0.18.1
    material_dialogs: ^1.1.4
    provider: ^6.0.5
    shared_preferences: ^2.2.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "lib/assets/logo.png"
    adaptive_icon_background: "lib/assets/logo.png"

flutter:
    uses-material-design: true
    assets:
        - lib/assets/
        - lib/assets/countries/
